project:
  type: website

website:
  title: "Onboarding"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - about.qmd
      - section: "Developers"
        contents:
          - developers/index.qmd
          - developers/version-control.qmd
          - developers/container-registry.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



